### PR TITLE
Add the option of running locally with Docker

### PR DESCRIPTION
**Pull request by bryik**
Cool game! I had a bit of trouble getting it running on my Macbook, ended up cobbling together Docker containers to make it work. There are some errors in the logs the first time `docker compose up` is run, but the game seems to operate alright.

Feel free to close this PR if y'all are not interested :-)

### CODE REVIEW

**Comment by li-boxuan** [comment]
Thank you very much! Was about to give up until I saw this. Works like a charm!

**Comment by PaulScotti** [comment]
Hell yeah thank you Ben!!

**Comment by PaulScotti** [comment]
I'm curious what the error you were getting with without Docker though?

**Comment by bryik** [comment]
> I'm curious what the error you were getting with without Docker though?

If I remember right, I think the API was failing for lack of a postgres database connection. Also, I wanted to use venv to manage dependencies instead of pipenv and missed psycopg's extra "pool" module (causing `ModuleNotFound` errors).

**Comment by PaulScotti** [comment]
Ah youre right! Thanks for pointing that out.

OK I think i fixed it now so that the game no longer breaks if DB_CONN_URL is not supplied as an env variable

https://github.com/ironman5366/ai-murder-mystery-hackathon/pull/17

**Pull request merged**
